### ISSUE TITLE
Preview of a bbcode using parser permissions doesn't work as expected

### ISSUE THREAD

**Issue by Xon** [cclaerhout/xen_BBM_v2#10]
When previewing a bbcode using parser permissions, the bbcode doesn't render if it is locked to a group the user making the post is a member of.

Likely this is a code-path not setting up the tag-map, and as such the parser permissions don't know about the use group properly.

**Comment by cclaerhout** [comment]
I'm going to follow your lead for this ; would it be just possible to keep brackets for conditionnals ? I prefere to keep the well organized structure for PHP ; for JS it's different ^^I'm going to follow your lead for this ; would it be just possible to keep brackets for conditionnals ? I prefere to keep the well organized structure for PHP ; for JS it's different ^^

**Comment by Xon** [comment]
Whoops. I normally put brackets around conditionals. I must have missed some. I'll re-tab this so the code matches the surrounding code.

**Comment by cclaerhout** [comment]
So your patch fixes this issue, can you confirm please, so it can be closed, thanks

**Comment by Xon** [comment]
Yes. I've been running this in production for ~2 days now and it is working fine.
