### ISSUE TITLE
During editing preview - The incorrect user id/groups are used for the post/message

### ISSUE THREAD

**Issue by Xon** [cclaerhout/xen_BBM_v2#15]
On double checking the recent commit, I've identified that the incorrect user id is being used on previewing edits for a post/conversation message owned by someone else.

This results in the potentially the wrong preview if the user's edited post has a different set of allowed bbcode to the viewing user at the time.

https://github.com/cclaerhout/xen_BBM_v2/commit/38199641ec05ddcf26c67b986707a83bff5c965b#diff-5c13f4d8690a639888b3e9d57014d6bcR2012
```
$this->_postsDatas = array(  
		$id => array( 
		'post_date' => XenForo_Application::$time,  
		'user_id' => $visitor['user_id'],  
```
Much like how $id is plucked out depending on if the preview is for a new post vs an edit, so to does the $user_id for the owner of the post.

I'll need to think about how this would affect the permission groups users. Thoughts?

**Comment by cclaerhout** [comment]
It can be modified, but is it worth it? Correct me if I'm wrong (it's late so I might): we're talking here about the parsing permissions, not the viewing ones. So we've got 2 usergroups: basic & admin. We're in a post message. We've got a "test" bbcode that the basic usergroup can't use, the admin can.

The basic usergroup creates a post message with the test Bb Code, it doesn't parse. The admin is going to edit it. The message information is about the creator of the message, it doesn't parse for the admin either (we might need to change this by the way). With the preview it can.

If you see any problem with it, we can still modify this (I've only tried for the post message - not conversation), this would work:
				$isNewMessage = (!isset($params['post']));

				if($isNewMessage)
				{
					//Generic data
					$this->_postsDatas = array( 
						0 => array(
							'post_date' => XenForo_Application::$time, 
							'user_id' => $visitor['user_id'], 
							'post_id' => 0, 
							'user_group_id' => $visitor['user_group_id'], 
							'secondary_group_ids' => $visitor['secondary_group_ids'],
							'message' => $params['message']
						)
					);
				}
				else
				{
					$this->_postsDatas = array( 
						0 => $params['post']
					);				
				}

				$this->_createBbCodesMap($this->_postsDatas);

**Comment by cclaerhout** [comment]
Well for conversation, it's even easier, just need to extend this:

				if (isset($params['message']['message']))
				{
					$id = $params['message']['message_id'];
					$message = $params['message']['message'];
				}

**Comment by Xon** [comment]
Yup, that describes the problem. Sorry about the somewhat rambling message, it was posted very late for myself.

Your proposed solution looks mostly right. Just the "0 =>" when we have a post should be $params['post']['post_id']. I'll work up a PR.

**Comment by cclaerhout** [comment]
Could you please try to edit (as an admin) a post that has been created by a user that doesn't have parsing permissions to use a Bb Code? I don't think the admin could see it either, the preview mode could be an alternative to see the Bb Code content.

**Comment by Xon** [comment]
Currently; As an admin, I can edit a normal user's posts and preview would show that the admin-only bbcode would work despite it not being representative.

**Comment by cclaerhout** [comment]
I've checked your commit, it's nice. Just one thought: I don't think this line is necessary:
				$params['conversationMessage']['message'] = $params['message'];
Both seem to have the same value

**Comment by cclaerhout** [comment]
By the way I'm using this addon https://github.com/xfrocks/DevHelper (from Xfrocks) to add files hashes.
That's really convenient on local installation. To make it work, I just had to edit the class DevHelper_Autoloader and comment this line: 

throw new XenForo_Exception('DevHelper_Autoloader must be used instead of XenForo_Autoloader');

After you need to create an export directory in the root of XenForo and then, in the addon you want to export, you need to create a config file:

<?php

class BBM_DevHelper_Config extends DevHelper_Config_Base
{
    protected $_dataClasses = array();
    protected $_dataPatches = array();
    protected $_exportPath = '/wamp/www/xenforo/sedo_export';
    protected $_exportIncludes = array();

    /**
     * Return false to trigger the upgrade!
     **/
    protected function _upgrade()
    {
        return true; // remove this line to trigger update

        /*
        $this->addDataClass(
            'name_here',
            array( // fields
                'field_here' => array(
                    'type' => 'type_here',
                    // 'length' => 'length_here',
                    // 'required' => true,
                    // 'allowedValues' => array('value_1', 'value_2'),
                    // 'default' => 0,
                    // 'autoIncrement' => true,
                ),
                // other fields go here
            ),
            array('primary_key_1', 'primary_key_2'), // or 'primary_key', both are okie
            array( // indeces
                array(
                    'fields' => array('field_1', 'field_2'),
                    'type' => 'NORMAL', // UNIQUE or FULLTEXT
                ),
            ),
        );
        */
    }
}

Once you get it, development is faster.

**Comment by Xon** [comment]
```
$params['conversationMessage']['message'] = $params['message'];
```
The left handside is the original message from before the edit while the right hand side is the new message.

**Comment by cclaerhout** [comment]
My bad ! Thank you ! Everything should be good now :)

**Comment by cclaerhout** [comment]
Oh I still would need to update Font Awesome
