### ISSUE TITLE
Pre-cache optimizations

### ISSUE THREAD

**Issue by Xon** [cclaerhout/xen_BBM_v2#20]
When enabled, the pre-caching function runs on content even if there is no tags that would benefit from it.

On the Base Formatter, we have the bb code map to tell us if a particular bit tag is used generally, or for a particular bit of content.

In this branch: https://github.com/Xon/xen_BBM_v2/tree/precache-patch-1 I've developed a solution where if no pre-cachable tags are used at all, it stops early. So far this looks to work fine, but I haven't had time todo extensive testing yet.

I want to improve it so it will know to skip individual content pieces (ie posts, signatures) if there is nothing todo.

**Comment by cclaerhout** [comment]
Thanks for this by the way, I forgot.

**Comment by Xon** [comment]
:+1:
